### PR TITLE
use .bower.json manifest instead of bower.json manifest

### LINKED ISSUE #29: not all bower dependencies have a "bower.json"
when bundling npm packages the root manifest is the same as a dependency manifest . -- both being package.json

when bundling bower packages the root manifest is bower.json and a dependency manifest is .bower.json

oax gets by most of the time because a dependency usually has a bower.json file

o-gallery depends on ftscroller which has no bower.json file and currently makes `oax` fail to bundle o-gallery.

### PR DESCRIPTION
**Pull request by JakeChampion**
not all bower dependencies have bower.json but they all have .bower.json

closes #29

### CODE REVIEW

**Comment by chee** [comment]
great:)!

**Review by chee — APPROVED** [review]
excellent!!!!

**Comment by chee** [comment]
i edited to add "closes #29" is that true?

**Comment by JakeChampion** [comment]
Is true

**Pull request merged**
