### PR TITLE
Skip missing optional dependencies

### PR DESCRIPTION
**Pull request by chee**
* also fail better in the future, by providing error messages that are better.
* also ensure we don't try getting the npm dev deps until we know the name of the input file

### CODE REVIEW

**Comment by chee** [comment]
@JakeChampion  This will fix o-tracking's build

**Review by JakeChampion — COMMENTED** [review]
Is it possible to add a test for this scenario?

**Comment by chee** [comment]
> Is it possible to add a test for this scenario?

done

**Review by JakeChampion — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v1.2.3 :tada:

**Pull request merged**
