### PR TITLE
Rename oax to scrumple

### PR DESCRIPTION
**Pull request by chee**
scrumple: the fast and scrappy way to make a bundle of some origami

### CODE REVIEW

**Comment by chee** [comment]
i'm going to update the README to contain some actual information here, and then tag this release:major

**Comment by chee** [comment]
then we can deprecate oax

**Review by notlee — APPROVED** [review]
:D

**Comment by chee** [comment]
link to the rendered README: https://github.com/Financial-Times/oax/blob/2f509dc178a7297af4ce6dd7a6bb5e7406872a42/README.md

**Review by JakeChampion — APPROVED** [review]
🦀

**Comment by JakeChampion** [comment]
:tada: This PR is included in version v1.0.0 :tada:

**Pull request merged**
